require(cluster)

#' Set working directory
if (dir.exists("/mnt/data/asis/untwist/")) {
  setwd("/mnt/data/asis/untwist/")
}

#' Load transposed accession coordinates generated by our principal component
#' analysis:
unt_coords <- read.table(
  "results/all_public_and_all_untwist_SNP_filtered_pca.rel",
  stringsAsFactors = FALSE
)
#' Read and set the row (accession) identifier. Clean them, because PLINK had
#' to duplicate them, see plink --double-id
unt_accession_names <- sub(
  "\\t\\S+$", "",
  readLines(
    "results/all_public_and_all_untwist_SNP_filtered_pca.rel.id"
  )
)
rownames(unt_coords) <- unt_accession_names

#' k-means clustering
k_range <- 3:10
unt_k_means <- lapply(k_range, function(k) {
  kmeans(unt_coords, centers = k, nstart = 25)
})

#' Elbow method generates a plot of the total sum of squares of clusters
#' variation, plots it and finds the bend "elbow" at the optimal k in the curve.
pdf("./results/k_means_elbow_plot_for_ata.pdf")
plot(
  x = k_range, y =
    unlist(lapply(unt_k_means, function(x) {
      x$tot.withinss
    })),
  xlab = "number of clusters (k)",
  ylab = "total within-cluster variation", type = "b"
)
dev.off()

# Use the Silhouette method to infer the best number of clusters
avg_sil <- function(km_res, dist_df) {
  ss <- silhouette(km_res$cluster, dist_df)
  mean(ss[, 3])
}

# Compute the average Silhouette width
unt_dist <- dist(unt_coords)
unt_k_means_sil <- lapply(unt_k_means, function(x) {
  avg_sil(x, unt_dist)
})

# Plot the Silhouette widths
pdf("./results/k_means_silhoutte_plot_for_ata.pdf")
plot(k_range, unt_k_means_sil,
  type = "b", pch = 19, frame = FALSE,
  xlab = "Number of clusters K",
  ylab = "Average Silhouettes"
)
dev.off()

# Visual inspection and an educated interpretation yields
# that k=3 and k=10 are good cluster numbers
unt_good_ks <- c(3, 10)
for (i in unt_good_ks) {
  pdf(paste0("./results/k_means_scatterplot_k=", i, "_for_ata.pdf"))
  kmeans_res <- unt_k_means[[toString(i)]]
  plot(
    x = unt_coords[, 1], y = unt_coords[, 2], type = "p", pch = ".",
    col = kmeans_res$cluster
  )
  # text(x = unt_coords[, 1], y = unt_coords[, 2],
  # labels=rownames(unt_coords), col=kmeans_res$cluster)
  dev.off()
}

#' hclust
unt_hclust <- hclust(dist(unt_coords), method = "average")
pdf("./results/hclust_tree_for_ata.pdf", width = 21, height = 7)
plot(unt_hclust, cex=0.5)
dev.off()
