require(cluster)

#' Set working directory
if (dir.exists("/mnt/data/asis/untwist/")) {
  setwd("/mnt/data/asis/untwist/")
}

#' Load transposed accession coordinates generated by our principal component
#' analysis:
unt_eigenvecs <- read.table(
  "results/all_public_and_all_untwist_SNP_filtered_pca.eigenvec",
  header = TRUE,
  quote = "",
  sep = "\t",
  stringsAsFactors = FALSE
)
#' Extract a table with _only_ the eigenvectors and rownames being the
#' accession identifiers:
unt_coords <- unt_eigenvecs[, colnames(unt_eigenvecs)[
  grepl("^PC\\d+$", colnames(unt_eigenvecs))
]]
rownames(unt_coords) <- unt_eigenvecs$IID

#' k-means clustering
k_range <- 3:10
unt_k_means <- setNames(lapply(k_range, function(k) {
  kmeans(unt_coords, centers = k, nstart = 25)
}), as.character(k_range))

#' Elbow method generates a plot of the total sum of squares of clusters
#' variation, plots it and finds the bend "elbow" at the optimal k in the curve.
pdf("./results/k_means_elbow_plot.pdf")
plot(
  x = k_range, y =
    unlist(lapply(unt_k_means, function(x) {
      x$tot.withinss
    })),
  xlab = "number of clusters (k)",
  ylab = "total within-cluster variation", type = "b"
)
dev.off()

# Use the Silhouette method to infer the best number of clusters
avg_sil <- function(km_res, dist_df) {
  ss <- silhouette(km_res$cluster, dist_df)
  mean(ss[, 3])
}

# Compute the average Silhouette width
unt_dist <- dist(unt_coords)
unt_k_means_sil <- lapply(unt_k_means, function(x) {
  avg_sil(x, unt_dist)
})

# Plot the Silhouette widths
pdf("./results/k_means_silhoutte_plot.pdf")
plot(k_range, unt_k_means_sil,
  type = "b", pch = 19, frame = FALSE,
  xlab = "Number of clusters K",
  ylab = "Average Silhouettes"
)
dev.off()

# Try different k ranging from 3,4,...,10:
unt_good_ks <- 3:10
unt_cex <- unlist(lapply(rownames(unt_coords), function(accession_id) {
  if (grepl("^UNT", accession_id)) {
    0.75
  } else {
    0.5
  }
}))
unt_labels <- sub(
  "_(reseq|new)$", "",
  sub("^CAMPUB", "C", sub("^UNT", "U", rownames(unt_coords)))
)
for (i in unt_good_ks) {
  pdf(paste0("./results/k_means_scatterplot_k=", i, ".pdf"))
  kmeans_res <- unt_k_means[[toString(i)]]
  plot(
    x = unt_coords[, 1], y = unt_coords[, 2], type = "n",
    main = paste0("k-means clustering result for k=", i),
    xlab = "1st principal component",
    ylab = "2nd principal component"
  )
  text(
    x = unt_coords[, 1], y = unt_coords[, 2], labels = unt_labels,
    col = kmeans_res$cluster, cex = unt_cex
  )
  dev.off()
  #' Save cluster results:
  kmeans_res_df <- as.data.frame(kmeans_res$cluster)
  colnames(kmeans_res_df) <- paste0("k-means-cluster_(k=", i, ")")
  kmeans_res_df$Accession <- rownames(kmeans_res_df)
  write.table(kmeans_res_df[, c(2, 1)],
    paste0("./results/k_means_result_k=", i, ".tsv"),
    row.names = FALSE,
    sep = "\t",
    quote = FALSE
  )
}
